name: Kill
on: workflow_dispatch

jobs:
  kill:
    runs-on: ubuntu-latest
    steps:
      - name: Kill service
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.PRIVATE_KEY }}
          passphrase: ${{ secrets.PASSPHRASE }}
          port: ${{ secrets.PORT }}
          script: |
            cd task-bot-rs
            ./kill.sh
            ps ux | grep bot | grep -v grep | grep -v bash
